In [2]:
import pandas as pd

In [3]:
dict1 = {
    'Name' : ['Priyang','Aadhya','Krishna','Vedant','Parshv','Mittal','Archana'],
    'Marks' : [90,89,99,87,90,83,99],
    'Gender' : ['Male','Female','Female','Male','Male','Female','Female']
}
df = pd.DataFrame(dict1)
df

      Name  Marks  Gender
0  Priyang     90    Male
1   Aadhya     89  Female
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [4]:
df.head(3)

      Name  Marks  Gender
0  Priyang     90    Male
1   Aadhya     89  Female
2  Krishna     99  Female

In [5]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [6]:
df.shape

(7, 3)

In [7]:
print('Number of rows',df.shape[0])
print('Number of columns',df.shape[1])

Number of rows 7
Number of columns 3

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [9]:
df.isnull().sum(axis=0)

Name      0
Marks     0
Gender    0
dtype: int64

In [11]:
df.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  91.000000     NaN
std         NaN   5.972158     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  94.500000     NaN
max         NaN  99.000000     NaN

In [12]:
df

      Name  Marks  Gender
0  Priyang     90    Male
1   Aadhya     89  Female
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [13]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
df['Gender'].nunique()

2

In [15]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [17]:
df[df['Marks'] >= 90]

      Name  Marks  Gender
0  Priyang     90    Male
2  Krishna     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [23]:
len(df[(df['Marks'] >= 90) & (df['Marks'] <= 100)])

4

In [24]:
sum(df['Marks'].between(90,100))

4

In [27]:
df['Marks'].mean()

np.float64(91.0)

In [30]:
def marks(x):
    return x/2

In [33]:
df['half_marks']= df['Marks'].apply(marks)
df

      Name  Marks  Gender  half_marks
0  Priyang     90    Male        45.0
1   Aadhya     89  Female        44.5
2  Krishna     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [34]:
df['Marks'].apply(lambda x:x/2)

0    45.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [35]:
df['Name'].apply(len)

0    7
1    6
2    7
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [37]:
df['Male_Female'] = df['Gender'].map({'Male':1,'Female':0})
df

      Name  Marks  Gender  half_marks  Male_Female
0  Priyang     90    Male        45.0            1
1   Aadhya     89  Female        44.5            0
2  Krishna     99  Female        49.5            0
3   Vedant     87    Male        43.5            1
4   Parshv     90    Male        45.0            1
5   Mittal     83  Female        41.5            0
6  Archana     99  Female        49.5            0

In [38]:
df.drop('Male_Female',axis=1)

      Name  Marks  Gender  half_marks
0  Priyang     90    Male        45.0
1   Aadhya     89  Female        44.5
2  Krishna     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [42]:
df.drop(['Male_Female','half_marks'],axis=1,inplace=True)

In [43]:
df

      Name  Marks  Gender
0  Priyang     90    Male
1   Aadhya     89  Female
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [44]:
df.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [45]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [48]:
df.sort_values(by='Marks')

      Name  Marks  Gender
5   Mittal     83  Female
3   Vedant     87    Male
1   Aadhya     89  Female
0  Priyang     90    Male
4   Parshv     90    Male
2  Krishna     99  Female
6  Archana     99  Female

In [50]:
df.sort_values(by=['Marks','Gender'],ascending=False)

      Name  Marks  Gender
2  Krishna     99  Female
6  Archana     99  Female
0  Priyang     90    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

In [54]:
df[df['Gender'] == 'Female'][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2  Krishna     99
5   Mittal     83
6  Archana     99

In [57]:
df[df['Gender'].isin(['Female'])][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2  Krishna     99
5   Mittal     83
6  Archana     99